cmake_minimum_required(VERSION 3.20 FATAL_ERROR)

project(TMPL VERSION 1.0 LANGUAGES C CXX)

set(TMPL_HOME ${CMAKE_CURRENT_LIST_DIR})

set(TMPL_INCLUDE_DIR ${TMPL_HOME}/include)
set(TMPL_SOURCES_DIR ${TMPL_HOME}/sources)

file(GLOB_RECURSE TMPL_PUBLIC_HEADERS CONFIGURE_DEPENDS
	${TMPL_INCLUDE_DIR}/*.hpp
	${TMPL_INCLUDE_DIR}/*.inl
	${TMPL_INCLUDE_DIR}/*.h
)

file(GLOB_RECURSE TMPL_SOURCES CONFIGURE_DEPENDS
	${TMPL_SOURCES_DIR}/*.cpp
	${TMPL_SOURCES_DIR}/*.c
	${TMPL_SOURCES_DIR}/*.hpp
	${TMPL_SOURCES_DIR}/*.inl
	${TMPL_SOURCES_DIR}/*.h
)

add_executable(tmpl ${TMPL_SOURCES} ${TMPL_PUBLIC_HEADERS})

target_include_directories(tmpl PUBLIC ${TMPL_INCLUDE_DIR})
